#!/usr/bin/env python3
"""Reproducibly extract family-2 TQX program bytes from the local reference PE.

The output retains proprietary reference machine code; it is not recovered
source or independently authored shader code. No device upload occurs.
"""
import hashlib
import json
from pathlib import Path
import struct
from pe_image import ReferencePE

ROOT = Path(__file__).resolve().parents[1]
p = ReferencePE('/opt/MTT-driver-only/mtkm64.sys')
image = bytearray()
records, states, maps = [], [], []
for base,count,alignment,kind in ((0x140b9ea30,121,32,'shader'),(0x140b9e850,10,16,'pds')):
    region_start = len(image)
    for index in range(count):
        q = struct.unpack('<6Q',p.read(base+index*48,48))
        assert q[2] == 0 and 0 < q[1] <= 220 and q[4] <= 64
        offset = len(image)-region_start
        code = p.read(q[0],q[1]*4)
        image.extend(code)
        image.extend(bytes((-len(image)) % alignment))
        entry = dict(kind=kind,index=index,offset=offset,code_dwords=q[1],
                     parameters=q[4],source=hex(q[0]),sha256=hashlib.sha256(code).hexdigest())
        if kind == 'shader':
            mapping = list(struct.unpack('<'+'Q'*q[4],p.read(q[5],q[4]*8))) if q[4] else []
            entry.update(outputs=q[3],map_start=len(maps))
            maps.extend(mapping)
        else:
            state = list(struct.unpack('<'+'I'*q[4],p.read(q[3],q[4]*4)))
            assert q[5] <= q[4]
            entry.update(patch_dword=q[5],state_start=len(states))
            states.extend(state)
        records.append(entry)
    if kind == 'shader': shader_bytes = len(image)

def array(name, ctype, values, per_line, fmt):
    lines = [f'static const {ctype} {name}[{len(values)}] = {{']
    for i in range(0,len(values),per_line):
        lines.append('\t'+', '.join(fmt(v) for v in values[i:i+per_line])+',')
    return '\n'.join(lines+['};'])

lines = ['/* Generated by scripts/extract-tqx-programs.py from local proprietary',
         ' * reference machine code, not recovered source. Do not hand-edit.',
         f' * Reference SHA-256: {p.sha256}', ' */',
         '#ifndef MT_GUEST_TQX_PROGRAM_DATA_H', '#define MT_GUEST_TQX_PROGRAM_DATA_H',
         f'#define MT_TQX_SHADER_BANK_BYTES {shader_bytes}U',
         f'#define MT_TQX_PROGRAM_BANK_BYTES {len(image)}U',
         'struct mt_tqx_shader_meta { u32 offset, code_dwords, outputs, parameters, map_start; };',
         'struct mt_tqx_pds_meta { u32 offset, code_dwords, parameters, patch_dword, state_start; };',
         array('mt_tqx_program_bytes','u8',image,16,lambda v:f'0x{v:02x}'),
         array('mt_tqx_parameter_map','u64',maps,6,lambda v:f'0x{v:x}ULL'),
         array('mt_tqx_pds_state','u32',states,6,lambda v:f'0x{v:08x}U'),
         'static const struct mt_tqx_shader_meta mt_tqx_shaders[121] = {']
for e in records[:121]:
    lines.append('\t{'+', '.join(str(e[n]) for n in ('offset','code_dwords','outputs','parameters','map_start'))+'},')
lines += ['};','static const struct mt_tqx_pds_meta mt_tqx_pds[10] = {']
for e in records[121:]:
    lines.append('\t{'+', '.join(str(e[n]) for n in ('offset','code_dwords','parameters','patch_dword','state_start'))+'},')
lines += ['};','#endif','']
(ROOT/'kernel/mt_tqx_program_data.h').write_text('\n'.join(lines))
dest = ROOT/'build/firmware/tqx-family2-programs.bin'
dest.parent.mkdir(parents=True, exist_ok=True)
dest.write_bytes(image)
report = dict(reference_sha256=p.sha256,family=2,shader_bytes=shader_bytes,
              pds_bytes=len(image)-shader_bytes,bank_bytes=len(image),
              bank_sha256=hashlib.sha256(image).hexdigest(),
              zeroed_alignment_padding=True,records=records,hardware_access=False)
(ROOT/'reports/tqx-program-extraction.json').write_text(json.dumps(report,indent=2)+'\n')
print(f'Extracted {len(records)} TQX programs: {len(image)} bytes; SHA-256 {report["bank_sha256"]}')
