#!/usr/bin/env python3
"""Extract 3D graphics context initial BO binary states into kernel/mt_gfx_context_data.h.

Reads build/r36-gfx-context/linux-base-bo-*.bin and formats C const arrays with digests.
"""
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / 'build/r36-gfx-context'
OUT_H = ROOT / 'kernel/mt_gfx_context_data.h'

def main():
    lines = [
        '/* SPDX-License-Identifier: GPL-2.0 */',
        '/* Generated by scripts/extract-gfx-context-data.py from verified reference state.',
        ' * Do not hand-edit.',
        ' */',
        '#ifndef MT_GUEST_GFX_CONTEXT_DATA_H',
        '#define MT_GUEST_GFX_CONTEXT_DATA_H',
        '',
        '#include <linux/types.h>',
        '#include "mt_gfx_context.h"',
        '',
    ]

    bo_metas = []
    for i in range(11):
        f = SRC_DIR / f'linux-base-bo-{i}.bin'
        data = f.read_bytes()
        digest = hashlib.sha256(data).hexdigest()
        bo_metas.append((i, len(data), digest))

        lines.append(f'/* BO {i}: {len(data)} bytes, sha256: {digest} */')
        lines.append(f'static const u8 mt_gfx_bo_{i}_init_data[{len(data)}] __maybe_unused = {{')
        for chunk_start in range(0, len(data), 16):
            chunk = data[chunk_start:chunk_start+16]
            hex_str = ', '.join(f'0x{b:02x}' for b in chunk)
            comma = ',' if chunk_start + 16 < len(data) else ''
            lines.append(f'\t{hex_str}{comma}')
        lines.append('};')
        lines.append('')

    lines.append('struct mt_gfx_bo_init_meta {')
    lines.append('\tu32 index;')
    lines.append('\tu32 bytes;')
    lines.append('\tconst u8 *data;')
    lines.append('};')
    lines.append('')
    lines.append('static const struct mt_gfx_bo_init_meta mt_gfx_bo_init_metas[MT_GFX_CONTEXT_BO_COUNT] __maybe_unused = {')
    for i, length, _ in bo_metas:
        lines.append(f'\t{{ {i}, {length}, mt_gfx_bo_{i}_init_data }},')
    lines.append('};')
    lines.append('')
    lines.append('static inline int mt_gfx_context_copy_bo_init(u32 index, void *dest, u32 capacity)')
    lines.append('{')
    lines.append('\tif (index >= MT_GFX_CONTEXT_BO_COUNT || !dest)')
    lines.append('\t\treturn -EINVAL;')
    lines.append('\tif (capacity < mt_gfx_bo_init_metas[index].bytes)')
    lines.append('\t\treturn -ENOSPC;')
    lines.append('\tmemcpy(dest, mt_gfx_bo_init_metas[index].data, mt_gfx_bo_init_metas[index].bytes);')
    lines.append('\treturn 0;')
    lines.append('}')
    lines.append('')
    lines.append('#endif /* MT_GUEST_GFX_CONTEXT_DATA_H */')
    lines.append('')

    OUT_H.write_text('\n'.join(lines))
    print(f"Generated {OUT_H} with {len(bo_metas)} BO initial data arrays.")

if __name__ == '__main__':
    main()
